### ISSUE TITLE
Auto completion doesn't work in IDEA(version 2018.3.5)

### ISSUE THREAD

**Issue by anicething** [mapstruct/mapstruct-idea#29] opened 2019-03-01 10:25 UTC

**Comment by VEINHORN** [comment] 2019-03-21 12:03
I have faced with the same issue in IDEA `2018.3.4`

**Comment by filiphr** [comment] 2019-03-23 08:34
If you can provide me with some IntelliJ logs or errors that are happening I would be able to help. Otherwise I can't really help as for me it used to work on 2018.3 (I am now on 2019.1 RC and it works there too)

**Comment by filiphr** [comment] 2019-06-16 08:48
Closing issue since I can't reproduce this.

**Comment by lkqm** [comment] 2019-08-26 02:02
Hi, Auto completion doesn't work, there is some enviroments info , and not error tips:

IntelliJ IDEA 2018.2.7 (Ultimate Edition)
Build #IU-182.5107.41, built on November 27, 2018
Licensed to jetbrains js
JRE: 1.8.0_152-release-1248-b22 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5

**Comment by Avinm** [comment] 2020-04-11 18:24
I could reproduce the same with https://github.com/mapstruct/mapstruct-idea/issues/39 on 2018.3.6 and mapstruct 1.3.1.Final

**Comment by filiphr** [comment] 2020-04-12 06:27
I'll reopen this one due to the reproducal from @Avinm (thanks for that). However, It seems that the gist works for me. Can you provide some details for the Java SDK that you are using perhaps?

**Comment by Avinm** [comment] 2020-04-12 10:33
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

**Comment by Avinm** [comment] 2020-05-09 04:38
For me this turned out to be mac hijacking the default (ctrl+space) shortcut for some reason:
Control-Space is reserved by OS X for changing keyboard layouts. Unintuitively, you have to enable the feature to disable the keyboard shortcut (and free up the key combo). 

Found the same problem listed at sublime forums: https://forum.sublimetext.com/t/os-x-control-space-not-working/2145/3
`Control-Space is reserved by OS X for changing keyboard layouts. Unintuitively, you have to enable the feature to disable the keyboard shortcut (and free up the key combo). To do this:`
````
    * Go to System Preferences > Language & Text > Input Sources
    * Check (turn on) at least two input sources in the left column
    * Click the “Keyboard Shortcuts…” button in the right column
    * Select Keyboard & Text Input on the left
    * Scroll to the bottom and disable “Select the previous input source – ^Space” on the right
    * Go back to System Preferences > Language & Text > Input Sources
    * Turn off the inputs on the left
````

**Comment by filiphr** [comment] 2020-05-10 11:38
Thanks for the information @Avinm. I am going to close this now since it seems we don't need to do anything.

**Closed by filiphr** 2020-05-10 11:38 UTC
