### ISSUE TITLE
Field prompt will fail when using @SuperBuilder

### ISSUE THREAD

**Issue by YAGAMIL** [mapstruct/mapstruct-idea#76] opened 2021-06-22 08:31 UTC
Other situations are good, but when I use Lombok's @SuperBuilder instead of @Builder, its field prompt will be invalid.

**Comment by filiphr** [comment] 2021-06-22 20:29
Thanks for raising this issue @YAGAMIL. I think that this is a duplicate of #44. Therefore, I am closing this in favour of that issue.

**Closed by filiphr** 2021-06-22 20:29 UTC
