### ISSUE TITLE
Refresh of generated mapper not working reliably

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct-idea#17] opened 2017-11-05 18:22 UTC
When altering a mapped type (e.g. the target type of a mapping method), mappers referring to that type aren't re-generated reliably.

I couldn't quite figure when it's working and when not, often I had to explicitly rebuild the entire project. I'd assume there's a way in IntelliJ plug-ins to mark a type (a mapper type) as dependent on other types (the source and target types of the mapper's methods), so a re-generation can be triggered in such case.

**Comment by filiphr** [comment] 2017-11-22 18:31
Closing it as duplicate of #13

**Closed by filiphr** 2017-11-22 18:31 UTC
