### ISSUE TITLE
Bug: smart completion doesn't work for "target" with Lombok @SuperBuilder

### ISSUE THREAD

**Issue by kagan94** [mapstruct/mapstruct-idea#44] opened 2020-05-19 09:17 UTC
Hi,
Thank you for great plugin! 👍👍👍 
It's really helpful during daily development.

I noticed that `Mapstruct IDEA plugin` doesn't support auto-completion for `target` attribute in `@Mapping` for latest `mapstruct` library.
However, auto-completion perfectly works for `source` attribute.

I have following setup and dependencies:
- IntelliJ IDEA 2019.2.4
- MapStruct Support IDEA plugin v. 1.1.1
- `org.mapstruct:mapstruct:1.3.1.Final`
- `org.projectlombok:lombok:1.18.12`

I noticed that `Mapstruct Support` stopped suggesting auto-completion after I upgraded mapstruct `1.2.0.Final -> 1.3.1.Final`.

**Comment by filiphr** [comment] 2020-05-19 19:54
Hey, thanks for the nice words, it is really appreciated.

Are you by any chance using Lombok builders? This might be related to #12.

To rule out Lombok, can you please delombok your class and check whether it is working properly?

Btw, which version of the Lombok plugin are you using? Can you also provide an example classes which are not working so I can try them out?

**Comment by filiphr** [comment] 2020-05-19 19:55
There is also #39 which seems related as well.

**Comment by kagan94** [comment] 2020-05-20 14:32
Good questions!

I investigated a bit and it's directly related to using `@SuperBuilder` which is experimental lombok feature:
https://projectlombok.org/features/experimental/SuperBuilder

Code example when auto-completion doesn't work:
```
//@SuperBuilder
@NoArgsConstructor
static class SuperExampleDto  {

}

@Getter
@Setter
@SuperBuilder
@NoArgsConstructor
static class ExampleDto extends SuperExampleDto  {
	private String name;
}

@Getter
static class Example  {
	private String name;
}
```

**Comment by filiphr** [comment] 2020-05-20 20:40
Thanks a lot. I'll give it a go with this example. It helps a lot having something that is easily reproducible.

**Comment by thunderhook** [comment] 2022-12-27 16:04
We are using `@SuperBuilder` for over a year now in different projects and never had any issues like that.
Seems that something between the plugin version 1.2.0 and 1.4.0 fixed that problem, since the reproducible example cannot be reproduced anymore.

@filiphr I think the ticket can be closed. Should i provide a regression test for this? I've seen no lombok tests, is this out of scope?

**Comment by filiphr** [comment] 2023-03-17 08:16
Thanks for the information @thunderhook. We don't really have tests with the lombok annotations and this is also a bit out of scope for this project.

I don't remember whether I checked the delomboked sources or not. Most likely it worked correctly. The most likely reason for this not being a problem anymore is that something was fixed in the Lombok IntelliJ plugin or in IntelliJ itself.

In any case, I am going to go ahead and close this issue now.

**Closed by filiphr** 2023-03-17 08:16 UTC
