### ISSUE TITLE
I can not make it work in Android Studio

### ISSUE THREAD

**Issue by sebasira** [mapstruct/mapstruct-idea#62] opened 2020-10-24 17:52 UTC
I'm trying to use this plugin in Android Studio (latests v4.1) and the autocomplete/assistant is not working while creating a `@Mapping`.

I mean, the suggestions for the `target` and `source` fields. If I manually write them I can navigate to them, they are recognize but there's no assistant while creating it.

I think that `Annotation Processor` was not enable, but it is. I'm also using **Lombok** and it's working fine (the Annotation Processor, I mean)

I think I'm missing something here but I can't figure out what.

Thank you!

**Comment by filiphr** [comment] 2020-10-25 13:51
Which version of the plugin are you using? 

Are suggestions missing in Java or Kotlin code?

In case you are using Lombok then it could be that the PSI from IntelliJ is not properly populated by the Lombok plugin. I would suggest trying to delombok your files and see if the suggestions work. Just to rule out Lombok.

**Comment by sebasira** [comment] 2020-10-25 17:50
I've recently installed the plugin (that same day), so I'm guessing it should be the latest. It's **v1.2.3**

Suggestions are missing in Java.

What I've try is removing the Lombok annotation from a class and manually create setter and getter, with the same result. Even try making the fields public.

I'll post a dummy code like the one I'm using, just in case you notice something


```java
@Data
@EqualsAndHashCode(callSuper = false)
public class A_createDTO extends CreateDTO<A> {
    private String name;
    private String lastname;
    private String city;
}
```

```java
@Mapper
public interface AMapper {
    @Mapping(target = "name", source = "nombre")
    @Mapping(target = "lastname", source = "apellido")
    @Mapping(target = "city", source = "ciudad")
    A_createDTO createMapper(B b);
}
```

Maybe I miss-understand the features of the plugin. What I'm expecting is that whenever I type an annotation like this one:

```java
@Mapping(target = "name", source = "nombre")
```

I start typing the target/source fields name an then I get the suggestions to prevent typos. Or after typing `target=` get a suggested list of all fields in the Target class.


And FWIW this is how I declare the MapStruct depencency:


```groovy
implementation 'org.mapstruct:mapstruct:1.4.1.Final'
annotationProcessor 'org.mapstruct:mapstruct-processor:1.4.1.Final'
testAnnotationProcessor 'org.mapstruct:mapstruct-processor:1.4.1.Final'
```

I'm aware that the `MapStruct` documentation also suggest this other lines in the `build.gradle` file:

```groovy
plugins {
    ...
    id 'net.ltgt.apt' version '0.15'
}

// You can integrate with your IDEs.
// See more details: https://github.com/tbroyer/gradle-apt-plugin#usage-with-ides
apply plugin: 'net.ltgt.apt-idea'
apply plugin: 'net.ltgt.apt-eclipse'
```

But I've remove those lines because the [readme of gradle-apt-plugin](https://github.com/tbroyer/gradle-apt-plugin) says the following:

>The goal of this plugin was to eventually no longer be needed, being superseded by built-in features. This has become a reality with Gradle 5.2 and IntelliJ IDEA 2019.1. **tl;dr: this plugin is obsolete, don't use it**. If you're using Eclipse though, continue reading.

I'm using Android Studio (based on InteliJ IDEA) and Gradle v6.5

**Comment by sebasira** [comment] 2020-10-27 12:44
More on this... same ins happening in IntelliJ IDEA, Spring Boot project (the Java backend of the previous mentioned Android app). 

I use the same setup, so definitely I'm missing a step or have something miss-configured and I can not figured out what.

Any input would be appreciated! Thank you!

**Comment by filiphr** [comment] 2020-10-31 12:18
>I start typing the target/source fields name an then I get the suggestions to prevent typos. Or after typing `target=` get a suggested list of all fields in the Target class.

The suggestions should be there after typing `target="<caret>"`. You have to be inside the quotes in order for the suggestions to work.

**Comment by sebasira** [comment] 2020-10-31 21:29
@filiphr thanks for your reply. 

Yes that is what I would expect, but look at this screenshot:

<img width="880" alt="Screen Shot 2020-10-31 at 18 25 29" src="https://user-images.githubusercontent.com/11217669/97790336-8e3fd080-1ba6-11eb-9432-7ba87d87f89d.png">

As you can see it IDE (signals that the property `vehicleAlias` is unmapped). *I think that feature is part of the plugin* so the plugin should be working. But when I have the cursor inside the quotes of the *target*, I get no suggestions. I also typed the first **v** (of vehicleAlias) and still no suggestion.

Any ideas?

**Comment by liaozan** [comment] 2020-12-12 09:33
I also encountered the same problem
`IntelliJ IDEA 2020.3 (Ultimate Edition)
Build #IU-203.5981.155, built on December 1, 2020`

**Comment by liaozan** [comment] 2021-01-18 16:17
any progress？

**Comment by filiphr** [comment] 2023-05-01 21:33
Closing this, since I can't reproduce this

**Closed by filiphr** 2023-05-01 21:33 UTC
