### ISSUE TITLE
Mapping enum with methods causes IDEA missing target mapping warnings that aren't valid

### ISSUE THREAD

**Issue by rtenhove** [mapstruct/mapstruct-idea#42] opened 2020-01-23 23:36 UTC
Given a Java enum:
```java
public enum Bar {
  ALPHA,
  BETA;

  public static Bar fromNumber(int i) {
    return ALPHA;  // keep compiler smiling
   }
}
```
and a similar enum:
```java
public enum Foo {
  ALPHA,
  BETA;
}
```
and a simple mapping between them:
```java
@Mapper
public interface MyMapper {
  MyMapper INSTANCE = Mappers.getMapper(MyMapper.class);

  Bar map(Foo source);
}
```
IntelliJ shows a warning for the map method: `Unmapped target property: fromNumber`. This is incorrect (and MapStruct's annotation processor does not warn about this).

Having the IDEA plug-in add
```java
  @Mapping(target = "fromNumber", ignore = true)
```
causes the annotation processor to fail with the very correct error `A source constant must be specified for mappings of an enum mapping method.`

It appears that the IDEA plug-in is incorrectly treating the `fromNumber` method as one of the enum's constant values. It should filter out things like methods.

Plug-in version is the latest (1.1.1).

**Comment by filiphr** [comment] 2020-05-31 13:38
This is actually a duplicate of #38 which has already been fixed on master. However, I'll add a test case for this just fo be sure we don't have a regression

**Closed** 2020-05-31 13:55 UTC
Labels: bug
