### ISSUE TITLE
Auto completion doesn't work in IDEA version 2019.2 with Lombok @Data

### ISSUE THREAD

**Issue by FLXT-Qi** [mapstruct/mapstruct-idea#39] opened 2019-11-22 12:23 UTC
the go to definition works fine, but cannot use auto-completion.

I have all the fields with lombok plugin and  @Data annotation.

Where can i find the error log for you?

**Comment by filiphr** [comment] 2019-11-23 10:25
We are using the IntelliJ PSI (Program Structure Interface) to get the getters and setters for the auto completion. Perhaps the Lombok Plugin doesn't expose them properly. We'll need to debug the plugin with the Lombok Plugin together to see why it isn't working.

**Comment by neowin35** [comment] 2020-03-10 15:12
This issue is not limited to version 2019.2 It was not working on any version of IDEA and any version of lombok and the plugin I used until now.

**Comment by Avinm** [comment] 2020-04-11 18:26
Can confirm that lombok added getters are accessible from PSI methods and the only functionality that seems to be breaking (At least for me) is completion. References seem to be resolved correctly once the mappings are defined (cmd+click works)

**Comment by filiphr** [comment] 2020-04-12 06:26
Thanks for the check @Avinm.

I am going to close this ticket since it seems like Lombok is not the problem.

@FLXT-Qi, @neowin35 please provide example files that can reproduce this problem so we can analyse it better.

**Closed by filiphr** 2020-04-12 06:26 UTC
