### ISSUE TITLE
Intellij plugin reports unmapped properties which are mapped in custom annotation

### ISSUE THREAD

**Issue by cvetan** [mapstruct/mapstruct-idea#118] opened 2022-12-07 14:25 UTC
In one mapper class we have multiple same mappings used in couple of mapping methods. For this we made custom annotations which contain these mappings. Plugin doesn't recognize those attributes and shows warning for "unmapped" fields, even tough fields are mapped and code built successfully.

**Comment by thunderhook** [comment] 2022-12-24 13:24
Can you provide a simple example ([minimal reproduciable](https://stackoverflow.com/help/minimal-reproducible-example) at best)?

**Comment by thunderhook** [comment] 2022-12-27 15:19
Do you mean mapping composition as seen [here in the reference documentation](https://mapstruct.org/documentation/stable/reference/html/#mapping-composition)?

**Comment by cvetan** [comment] 2022-12-27 16:01
I'll send you example from my code. Just to get to my computer.

**Comment by Chr3is** [comment] 2023-02-06 14:03
same applies to mappers who inherit configuration from another mapper e.g.
```
import org.mapstruct.InheritConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Mapper
public interface Demo {

    @Mapping(source = "fieldOne", target = "field1")
    @Mapping(source = "fieldTwo", target = "field2")
    TargetObject1 sourceToTarget1(SourceObject address);

    @InheritConfiguration(name = "sourceToTarget1")
    @Mapping(source = "fieldThree", target = "field3")
    TargetObject2 sourceToTarget2(SourceObject address);

    @Data
    class SourceObject {

        private String fieldOne;

        private String fieldTwo;

        private String fieldThree;
    }

    @Data
    class TargetObject1 {

        protected String field1;

        protected String field2;
    }

    @EqualsAndHashCode(callSuper = true)
    @Data
    class TargetObject2 extends TargetObject1 {

        private String field3;
    }
}
```

Generated code

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2023-02-06T14:55:49+0100",
    comments = "version: 1.5.3.Final, compiler: javac, environment: Java 17.0.6 (Eclipse Adoptium)"
)
public class DemoImpl implements Demo {

    @Override
    public TargetObject1 sourceToTarget1(SourceObject address) {
        if ( address == null ) {
            return null;
        }

        TargetObject1 targetObject1 = new TargetObject1();

        targetObject1.setField1( address.getFieldOne() );
        targetObject1.setField2( address.getFieldTwo() );

        return targetObject1;
    }

    @Override
    public TargetObject2 sourceToTarget2(SourceObject address) {
        if ( address == null ) {
            return null;
        }

        TargetObject2 targetObject2 = new TargetObject2();

        targetObject2.setField3( address.getFieldThree() );
        targetObject2.setField1( address.getFieldOne() );
        targetObject2.setField2( address.getFieldTwo() );

        return targetObject2;
    }
}
```

<img width="733" alt="Bildschirm­foto 2023-02-06 um 15 02 43" src="https://user-images.githubusercontent.com/17119245/216991518-b416bd39-6671-44ba-b5c2-5e42a2d1f0cc.png">

Intellij: Build #IU-223.8617.56, built on January 26, 2023
MapStruct Plugin: 1.4.0

**Comment by filiphr** [comment] 2023-04-02 15:28
Closing this as a duplicate of #65

**Closed by filiphr** 2023-04-02 15:28 UTC
