### ISSUE TITLE
Completion of target and source properties in @Mapping doesn't work

### ISSUE THREAD

**Issue by dimamj** [mapstruct/mapstruct-idea#75] opened 2021-05-21 15:26 UTC
Hi. I've installed plugin to IDEA 2020.3 and completion doesn't work for me :( 

But I can go to declarations and use completion in expressions (they have a bit different color).
I also use Lombok `@Data`

Could you help me to fix this ?

Thanks.

**Comment by filiphr** [comment] 2021-05-21 17:30
I think that this is a duplicate of #39. 

I would suggest doing a delombok and seeing if it works. If it does then it is not a MapStruct problem, but rather a Lombok one and in this case you'll need to open an issue in the IntelliJ [issue tracker](https://youtrack.jetbrains.com/)

**Comment by dennisdaotvlk** [comment] 2021-07-09 03:50
Not working on `target` for me either in `Kotlin` or `Java` interface

**Comment by Connon-** [comment] 2021-07-30 13:33
I hope this problem can be solved quickly, It is a disaster to mapping my entities. 😭

**Comment by daniel-shuy** [comment] 2021-08-03 09:56
Try adding `lombok-mapstruct-binding` and see if it helps

**Comment by filiphr** [comment] 2021-08-14 07:28
The `lombok-mapstruct-binding` has no influence on the IntelliJ plugin.

@Connon- and @dennisdaotvlk if you want this to be resolved then please do what I suggested in https://github.com/mapstruct/mapstruct-idea/issues/75#issuecomment-846122182.

Without an example that shows this problem we cannot fix this, since I haven't been able to reproduce it

**Comment by Lee7b** [comment] 2021-09-21 18:44
Auto complete for source and target is not working for me either.

**Comment by Blackcbears** [comment] 2021-09-26 03:46
I also have the same problem。 crtl+ space to work。but normal doesn't work.
IDEA: 2021.2.2
mapstruct support: 1.3.0
system: win10

**Comment by cai200631** [comment] 2021-09-27 09:49
the same problem。 crtl+ space to work, but normal doesn't work.
also, when class field rename to new name,  @Mapping uses field name is not rename;

**Comment by filiphr** [comment] 2021-09-27 14:56
>crtl+ space to work。but normal doesn't work.

There is no such thing as normal. If you want to request auto complete support in a place like this you have to request it. If someone has a better idea for how this can work out-of-the-box I am open to ideas.

>also, when class field rename to new name, @mapping uses field name is not rename;

@cai200631 I do not understand what you mean with this. Please create another issue for this.

**Comment by filiphr** [comment] 2021-09-27 14:57
Since people have reported that requesting the auto complete works I am going to go ahead and close this issue

**Closed by filiphr** 2021-09-27 14:57 UTC
